#Elastic search 
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: myElastic
spec:
  version: 7.9.0
  nodeSets:
  - name: master-nodes
    count: 1
    config:
      node.master: true
      node.data: false
  - name: data-nodes
    count: 1
    config:
      node.master: false
      node.data: true
---
#Kibana
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: myKibana
spec:
  version: 7.9.0
  count: 1
  elasticsearchRef:
  - name: myElastic
